const subjects = {
  "Minerva McGonagall": "Transmutacja",
  "Severus Snape": "Eliksiry",
  "Rubeus Hagrid": "Opieka nad Magicznymi Stworzeniami",
  "Remus Lupin": "Obrona przed Czarną Magią",
  "Alastor Moody": "Obrona przed Czarną Magią",
  "Dolores Umbridge": "Obrona przed Czarną Magią",
  "Gilderoy Lockhart": "Obrona przed Czarną Magią",
  "Sybill Trelawney": "Wróżbiarstwo",
  "Filius Flitwick": "Zaklęcia",
  "Pomona Sprout": "Zielarstwo",
  "Horace Slughorn": "Eliksiry",
  "Charity Burbage": "Studia Mugoloznawcze",
  "Aurora Sinistra": "Astronomia",
  "Rolanda Hooch": "Latanie na miotle",
  "Irma Pince": "Bibliotekarka Hogwartu",
  "Argus Filch": "Woźny Hogwartu",
  "Poppy Pomfrey": "Uzdrowicielka / Skrzydło szpitalne",
  "Quirinus Quirrell": "Obrona przed Czarną Magią",
  "Cuthbert Binns": "Historia Magii",
  "Bathsheba Babbling": "Starożytne Runy",
  "Silvanus Kettleburn": "Opieka nad Magicznymi Stworzeniami",
};

